<a href="https://colab.research.google.com/github/songgplant/DL_basicstudy/blob/master/%ED%85%8D%EC%8A%A4%ED%8A%B8_%EC%A0%84%EC%B2%98%EB%A6%AC_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 17장 딥러닝을 이용한 자연어 처리

## 1. 텍스트의 토큰화

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding
from tensorflow.keras.utils import to_categorical
from numpy import array

In [5]:
# 케라스의 텍스트 전처리와 관련한 함수 중 text_to_word_sequence 함수를 불러옵니다.
from tensorflow.keras.preprocessing.text import text_to_word_sequence
 
# 전처리할 텍스트를 정합니다.
# text = '해보지 않으면 해낼 수 없다'
# text = '한편, GS리테일은 앞서 침수 우려 지역 편의점 매장의 피해를 막기 위해 모래주머니와 차수판 등을 지급했으며, 가맹점주의 개인 재산 피해는 상생 차원에서 마련한 특별재해지원금으로 지원할 예정이다.'
text = "이번 태풍으로 부산 해운대 바다 바로 앞, 80층이 넘는 초고층 아파트들이 밀집한 '부산 최고 부촌'인 마린시티가 또 쑥대밭이 됐습니다.침수를 막으려고 모래주머니를 쌓고, 차수벽을 설치하고, 쇠기둥으로 상가 입구를 막으며 대비했지만, 모두 무용지물이었습니다."

# 해당 텍스트를 토큰화합니다.
result = text_to_word_sequence(text)
print("\n원문:\n", text)
print("\n토큰화:\n", result)


원문:
 이번 태풍으로 부산 해운대 바다 바로 앞, 80층이 넘는 초고층 아파트들이 밀집한 '부산 최고 부촌'인 마린시티가 또 쑥대밭이 됐습니다.침수를 막으려고 모래주머니를 쌓고, 차수벽을 설치하고, 쇠기둥으로 상가 입구를 막으며 대비했지만, 모두 무용지물이었습니다.

토큰화:
 ['이번', '태풍으로', '부산', '해운대', '바다', '바로', '앞', '80층이', '넘는', '초고층', '아파트들이', '밀집한', "'부산", '최고', "부촌'인", '마린시티가', '또', '쑥대밭이', '됐습니다', '침수를', '막으려고', '모래주머니를', '쌓고', '차수벽을', '설치하고', '쇠기둥으로', '상가', '입구를', '막으며', '대비했지만', '모두', '무용지물이었습니다']


토큰화된 단어를 수치화시켜야 한다. 빈도수 세기로 넘버링을 진행, 빈출 단어가 아닌 것은 분석 단어에서 제외시키는 등 전처리

In [6]:
# 단어 빈도수 세기

# 전처리하려는 세 개의 문장을 정합니다.
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]
 
# 토큰화 함수를 이용해 전처리 하는 과정입니다.
token = Tokenizer()            # 토큰화 함수 지정
token.fit_on_texts(docs)       # 토큰화 함수에 문장 적용

In [7]:
# 단어의 빈도수를 계산한 결과를 각 옵션에 맞추어 출력합니다.
# Tokenizer()의 word_counts 함수는 순서를 기억하는 OrderedDict 클래스를 사용합니다.
print("\n단어 카운트:\n", token.word_counts) 

# 출력되는 순서는 랜덤입니다. 
print("\n문장 카운트: ", token.document_count)
print("\n각 단어가 몇 개의 문장에 포함되어 있는가:\n", token.word_docs)
print("\n각 단어에 매겨진 인덱스 값:\n",  token.word_index)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트:  3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'먼저': 1, '각': 1, '나누어': 1, '토큰화합니다': 1, '단어를': 1, '텍스트의': 2, '인식됩니다': 1, '딥러닝에서': 2, '단어로': 1, '토큰화해야': 1, '토큰화한': 1, '있습니다': 1, '수': 1, '사용할': 1, '결과는': 1})

각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


## 2. 단어의 원-핫 인코딩

In [8]:
text="오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"
token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [9]:
x=token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [10]:
# 인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


## 4.텍스트를 읽고 긍정, 부정 예측하기

In [12]:
# 텍스트 리뷰 자료를 지정합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0]) # 앞에 5개 긍정, 뒤에 5개 부정

# 토큰화 
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)


{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [13]:
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x)


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [14]:
# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.
padded_x = pad_sequences(x, 4)  
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [15]:
# 임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index) +1

# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4)) # 갖고 있는 모든 단어를 8자리로 만든다. 4개의 데이터를 넣는다.
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              168       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 1s 815ms/step - loss: 0.6944 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6921 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6899 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6876 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6854 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6832 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6809 - accuracy: 0.7000
Epoch 8/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6787 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6765 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6743 - accuracy: 0.8000
Epoch 11/20
1/1 [===================